version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/opt/app/api
    environment:
      API_SERVER_HOST: ""
      API_SERVER_PORT: "3000"
      MONGO_SERVER_HOST: "mongo"
      MONGO_SERVER_PORT: "27017"
      MONGO_SERVER_DATABASE: "authentication"
      CLIENT_PROTOCOL: "http"
      CLIENT_DOMAIN: "localhost"
      CLIENT_PORT: "4000"
    ports:
      - "3000:3000"
    networks:
      - kafka_network
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - kafka_network
networks:
  kafka_network:
    name: kafka_test_network

